[green_agent]
# Tu ID de agente evaluador
agentbeats_id = "019c1809-f7e4-7cc2-8eb7-958e92078fde"
env = { GOOGLE_API_KEY = "${GOOGLE_API_KEY}" }

[[participants]]
# Dejamos el ID vacío para que los que hagan Fork lo completen con su propio agente
agentbeats_id = ""
name = "salesforce_participant"
env = { GOOGLE_API_KEY = "${GOOGLE_API_KEY}" }

[config]
# Estos son los parámetros que tu código de Agent (Verde) recibe al inicio
domain = "salesforce"
num_tasks = 5
dataset_name = "Salesforce/CRMArena"
