[green_agent]
agentbeats_id = "019c1809-f7e4-7cc2-8eb7-958e92078fde"
env = { OPENAI_API_KEY = "${OPENAI_API_KEY}" }

[[participants]]
agentbeats_id = "019c181e-efc1-7312-b55e-c13cee824550"
name = "salesforce_participant"
env = { OPENAI_API_KEY = "${OPENAI_API_KEY}" }

[config]
domain = "salesforce"
num_tasks = 2
